# A list of lists, where each inner list is an evolutionary line.
# All names should be lowercase and match the filenames (e.g., 'nidoran-m').
evolution_lines = [
    ['abra', 'kadabra', 'alakazam'],
    ['absol'],
    ['aerodactyl'],
    ['aipom', 'ambipom'],
    ['alomomola'],
    ['amaura', 'aurorus'],
    ['anorith', 'armaldo'],
    ['applin', 'appletun'],
    ['applin', 'dipplin', 'hydrapple'],
    ['applin', 'flapple'],
    ['arceus'],
    ['archen', 'archeops'],
    ['arctovish'],
    ['arctozolt'],
    ['aron', 'lairon', 'aggron'],
    ['arrokuda', 'barraskewda'],
    ['articuno'],
    ['audino'],
    ['axew', 'fraxure', 'haxorus'],
    ['azelf'],
    ['azurill', 'marill', 'azumarill'],
    ['bagon', 'shelgon', 'salamence'],
    ['baltoy', 'claydol'],
    ['barboach', 'whiscash'],
    ['basculin', 'basculegion'],
    ['beldum', 'metang', 'metagross'],
    ['bellsprout', 'weepinbell', 'victreebel'],
    ['bergmite', 'avalugg'],
    ['bidoof', 'bibarel'],
    ['binacle', 'barbaracle'],
    ['blacephalon'],
    ['blipbug', 'dottler', 'orbeetle'],
    ['blitzle', 'zebstrika'],
    ['bombirdier'],
    ['bonsly', 'sudowoodo'],
    ['bouffalant'],
    ['bounsweet', 'steenee', 'tsareena'],
    ['bramblin', 'brambleghast'],
    ['bronzor', 'bronzong'],
    ['brute-bonnet'],
    ['bruxish'],
    ['budew', 'roselia', 'roserade'],
    ['buizel', 'floatzel'],
    ['bulbasaur', 'ivysaur', 'venusaur'],
    ['buneary', 'lopunny'],
    ['bunnelby', 'diggersby'],
    ['burmy', 'mothim'],
    ['burmy', 'wormadam'],
    ['buzzwole'],
    ['cacnea', 'cacturne'],
    ['calyrex'],
    ['capsakid', 'scovillain'],
    ['carbink'],
    ['carnivine'],
    ['carvanha', 'sharpedo'],
    ['castform'],
    ['caterpie', 'metapod', 'butterfree'],
    ['celebi'],
    ['celesteela'],
    ['cetoddle', 'cetitan'],
    ['charcadet', 'armarouge'],
    ['charcadet', 'ceruledge'],
    ['charmander', 'charmeleon', 'charizard'],
    ['chatot'],
    ['cherubi', 'cherrim'],
    ['chespin', 'quilladin', 'chesnaught'],
    ['chewtle', 'drednaw'],
    ['chi-yu'],
    ['chien-pao'],
    ['chikorita', 'bayleef', 'meganium'],
    ['chimchar', 'monferno', 'infernape'],
    ['chinchou', 'lanturn'],
    ['chingling', 'chimecho'],
    ['clamperl', 'gorebyss'],
    ['clamperl', 'huntail'],
    ['clauncher', 'clawitzer'],
    ['cleffa', 'clefairy', 'clefable'],
    ['clobbopus', 'grapploct'],
    ['cobalion'],
    ['combee', 'vespiquen'],
    ['comfey'],
    ['corphish', 'crawdaunt'],
    ['corsola', 'cursola'],
    ['cosmog', 'cosmoem', 'lunala'],
    ['cosmog', 'cosmoem', 'solgaleo'],
    ['cottonee', 'whimsicott'],
    ['crabrawler', 'crabominable'],
    ['cramorant'],
    ['cranidos', 'rampardos'],
    ['cresselia'],
    ['croagunk', 'toxicroak'],
    ['cryogonal'],
    ['cubchoo', 'beartic'],
    ['cubone', 'marowak'],
    ['cufant', 'copperajah'],
    ['cutiefly', 'ribombee'],
    ['cyclizar'],
    ['cyndaquil', 'quilava', 'typhlosion'],
    ['darkrai'],
    ['darumaka', 'darmanitan'],
    ['dedenne'],
    ['deerling', 'sawsbuck'],
    ['deino', 'zweilous', 'hydreigon'],
    ['delibird'],
    ['deoxys'],
    ['dewpider', 'araquanid'],
    ['dhelmise'],
    ['dialga'],
    ['diancie'],
    ['diglett', 'dugtrio'],
    ['ditto'],
    ['doduo', 'dodrio'],
    ['dondozo'],
    ['dracovish'],
    ['dracozolt'],
    ['drampa'],
    ['dratini', 'dragonair', 'dragonite'],
    ['dreepy', 'drakloak', 'dragapult'],
    ['drifloon', 'drifblim'],
    ['drilbur', 'excadrill'],
    ['drowzee', 'hypno'],
    ['druddigon'],
    ['ducklett', 'swanna'],
    ['dunsparce', 'dudunsparce'],
    ['duraludon', 'archaludon'],
    ['durant'],
    ['duskull', 'dusclops', 'dusknoir'],
    ['dwebble', 'crustle'],
    ['eevee', 'espeon'],
    ['eevee', 'flareon'],
    ['eevee', 'glaceon'],
    ['eevee', 'jolteon'],
    ['eevee', 'leafeon'],
    ['eevee', 'sylveon'],
    ['eevee', 'umbreon'],
    ['eevee', 'vaporeon'],
    ['eiscue'],
    ['ekans', 'arbok'],
    ['electrike', 'manectric'],
    ['elekid', 'electabuzz', 'electivire'],
    ['elgyem', 'beheeyem'],
    ['emolga'],
    ['enamorus'],
    ['entei'],
    ['espurr', 'meowstic'],
    ['eternatus'],
    ['exeggcute', 'exeggutor'],
    ['falinks'],
    ['farfetchd', 'sirfetchd'],
    ['feebas', 'milotic'],
    ['fennekin', 'braixen', 'delphox'],
    ['ferroseed', 'ferrothorn'],
    ['fezandipiti'],
    ['fidough', 'dachsbun'],
    ['finizen', 'palafin'],
    ['finneon', 'lumineon'],
    ['flabebe', 'floette', 'florges'],
    ['flamigo'],
    ['fletchling', 'fletchinder', 'talonflame'],
    ['flittle', 'espathra'],
    ['flutter-mane'],
    ['fomantis', 'lurantis'],
    ['foongus', 'amoonguss'],
    ['frigibax', 'arctibax', 'baxcalibur'],
    ['frillish', 'jellicent'],
    ['froakie', 'frogadier', 'greninja'],
    ['fuecoco', 'crocalor', 'skeledirge'],
    ['furfrou'],
    ['gastly', 'haunter', 'gengar'],
    ['genesect'],
    ['geodude', 'graveler', 'golem'],
    ['gible', 'gabite', 'garchomp'],
    ['gimmighoul', 'gholdengo'],
    ['girafarig', 'farigiraf'],
    ['giratina'],
    ['glameow', 'purugly'],
    ['glastrier'],
    ['gligar', 'gliscor'],
    ['glimmet', 'glimmora'],
    ['goldeen', 'seaking'],
    ['golett', 'golurk'],
    ['goomy', 'sliggoo', 'goodra'],
    ['gossifleur', 'eldegoss'],
    ['gothita', 'gothorita', 'gothitelle'],
    ['gouging-fire'],
    ['great-tusk'],
    ['greavard', 'houndstone'],
    ['grimer', 'muk'],
    ['grookey', 'thwackey', 'rillaboom'],
    ['groudon'],
    ['growlithe', 'arcanine'],
    ['grubbin', 'charjabug', 'vikavolt'],
    ['gulpin', 'swalot'],
    ['guzzlord'],
    ['happiny', 'chansey', 'blissey'],
    ['hatenna', 'hattrem', 'hatterene'],
    ['hawlucha'],
    ['heatmor'],
    ['heatran'],
    ['helioptile', 'heliolisk'],
    ['heracross'],
    ['hippopotas', 'hippowdon'],
    ['ho-oh'],
    ['honedge', 'doublade', 'aegislash'],
    ['hoopa'],
    ['hoothoot', 'noctowl'],
    ['hoppip', 'skiploom', 'jumpluff'],
    ['horsea', 'seadra', 'kingdra'],
    ['houndour', 'houndoom'],
    ['igglybuff', 'jigglypuff', 'wigglytuff'],
    ['illumise'],
    ['impidimp', 'morgrem', 'grimmsnarl'],
    ['indeedee'],
    ['inkay', 'malamar'],
    ['iron-boulder'],
    ['iron-bundle'],
    ['iron-crown'],
    ['iron-hands'],
    ['iron-jugulis'],
    ['iron-leaves'],
    ['iron-moth'],
    ['iron-thorns'],
    ['iron-treads'],
    ['iron-valiant'],
    ['jangmo-o', 'hakamo-o', 'kommo-o'],
    ['jirachi'],
    ['joltik', 'galvantula'],
    ['kabuto', 'kabutops'],
    ['kangaskhan'],
    ['karrablast', 'escavalier'],
    ['kartana'],
    ['kecleon'],
    ['keldeo'],
    ['klawf'],
    ['klefki'],
    ['klink', 'klang', 'klinklang'],
    ['koffing', 'weezing'],
    ['komala'],
    ['koraidon'],
    ['krabby', 'kingler'],
    ['kricketot', 'kricketune'],
    ['kubfu', 'urshifu'],
    ['kyogre'],
    ['kyurem'],
    ['landorus'],
    ['lapras'],
    ['larvesta', 'volcarona'],
    ['larvitar', 'pupitar', 'tyranitar'],
    ['latias'],
    ['latios'],
    ['lechonk', 'oinkologne'],
    ['ledyba', 'ledian'],
    ['lickitung', 'lickilicky'],
    ['lileep', 'cradily'],
    ['lillipup', 'herdier', 'stoutland'],
    ['litleo', 'pyroar'],
    ['litten', 'torracat', 'incineroar'],
    ['litwick', 'lampent', 'chandelure'],
    ['lotad', 'lombre', 'ludicolo'],
    ['lugia'],
    ['lunatone'],
    ['luvdisc'],
    ['machop', 'machoke', 'machamp'],
    ['magby', 'magmar', 'magmortar'],
    ['magearna'],
    ['magikarp', 'gyarados'],
    ['magnemite', 'magneton', 'magnezone'],
    ['makuhita', 'hariyama'],
    ['mankey', 'primeape', 'annihilape'],
    ['mantyke', 'mantine'],
    ['maractus'],
    ['mareanie', 'toxapex'],
    ['mareep', 'flaaffy', 'ampharos'],
    ['marshadow'],
    ['maschiff', 'mabosstiff'],
    ['mawile'],
    ['meditite', 'medicham'],
    ['melmetal'],
    ['meloetta'],
    ['meltan'],
    ['meowth', 'perrserker'],
    ['meowth', 'persian'],
    ['mesprit'],
    ['mew'],
    ['mewtwo'],
    ['mienfoo', 'mienshao'],
    ['milcery', 'alcremie'],
    ['miltank'],
    ['mime-jr', 'mr-mime', 'mr-rime'],
    ['mimikyu'],
    ['minccino', 'cinccino'],
    ['minior'],
    ['minun'],
    ['miraidon'],
    ['misdreavus', 'mismagius'],
    ['moltres'],
    ['morelull', 'shiinotic'],
    ['morpeko'],
    ['mudbray', 'mudsdale'],
    ['mudkip', 'marshtomp', 'swampert'],
    ['munchlax', 'snorlax'],
    ['munkidori'],
    ['munna', 'musharna'],
    ['murkrow', 'honchkrow'],
    ['nacli', 'naclstack', 'garganacl'],
    ['natu', 'xatu'],
    ['necrozma'],
    ['nickit', 'thievul'],
    ['nidoran-f', 'nidorina', 'nidoqueen'],
    ['nidoran-m', 'nidorino', 'nidoking'],
    ['nihilego'],
    ['nincada', 'ninjask'],
    ['nincada', 'shedinja'],
    ['noibat', 'noivern'],
    ['nosepass', 'probopass'],
    ['numel', 'camerupt'],
    ['nymble', 'lokix'],
    ['oddish', 'gloom', 'bellossom'],
    ['oddish', 'gloom', 'vileplume'],
    ['ogerpon'],
    ['okidogi'],
    ['omanyte', 'omastar'],
    ['onix', 'steelix'],
    ['oranguru'],
    ['oricorio'],
    ['orthworm'],
    ['oshawott', 'dewott', 'samurott'],
    ['pachirisu'],
    ['palkia'],
    ['pancham', 'pangoro'],
    ['panpour', 'simipour'],
    ['pansage', 'simisage'],
    ['pansear', 'simisear'],
    ['paras', 'parasect'],
    ['passimian'],
    ['patrat', 'watchog'],
    ['pawmi', 'pawmo', 'pawmot'],
    ['pawniard', 'bisharp', 'kingambit'],
    ['pecharunt'],
    ['petilil', 'lilligant'],
    ['phanpy', 'donphan'],
    ['phantump', 'trevenant'],
    ['pheromosa'],
    ['phione', 'manaphy'],
    ['pichu', 'pikachu', 'raichu'],
    ['pidgey', 'pidgeotto', 'pidgeot'],
    ['pidove', 'tranquill', 'unfezant'],
    ['pikipek', 'trumbeak', 'toucannon'],
    ['pincurchin'],
    ['pineco', 'forretress'],
    ['pinsir'],
    ['piplup', 'prinplup', 'empoleon'],
    ['plusle'],
    ['poipole', 'naganadel'],
    ['poliwag', 'poliwhirl', 'politoed'],
    ['poliwag', 'poliwhirl', 'poliwrath'],
    ['poltchageist', 'sinistcha'],
    ['ponyta', 'rapidash'],
    ['poochyena', 'mightyena'],
    ['popplio', 'brionne', 'primarina'],
    ['porygon', 'porygon2', 'porygon-z'],
    ['psyduck', 'golduck'],
    ['pumpkaboo', 'gourgeist'],
    ['purrloin', 'liepard'],
    ['pyukumuku'],
    ['quaxly', 'quaxwell', 'quaquaval'],
    ['qwilfish', 'overqwil'],
    ['raging-bolt'],
    ['raikou'],
    ['ralts', 'kirlia', 'gallade'],
    ['ralts', 'kirlia', 'gardevoir'],
    ['rattata', 'raticate'],
    ['rayquaza'],
    ['regice'],
    ['regidrago'],
    ['regieleki'],
    ['regigigas'],
    ['regirock'],
    ['registeel'],
    ['relicanth'],
    ['rellor', 'rabsca'],
    ['remoraid', 'octillery'],
    ['reshiram'],
    ['rhyhorn', 'rhydon', 'rhyperior'],
    ['riolu', 'lucario'],
    ['roaring-moon'],
    ['rockruff', 'lycanroc'],
    ['roggenrola', 'boldore', 'gigalith'],
    ['rolycoly', 'carkol', 'coalossal'],
    ['rookidee', 'corvisquire', 'corviknight'],
    ['rotom'],
    ['rowlet', 'dartrix', 'decidueye'],
    ['rufflet', 'braviary'],
    ['sableye'],
    ['salandit', 'salazzle'],
    ['sandile', 'krokorok', 'krookodile'],
    ['sandshrew', 'sandslash'],
    ['sandy-shocks'],
    ['sandygast', 'palossand'],
    ['sawk'],
    ['scatterbug', 'spewpa', 'vivillon'],
    ['scorbunny', 'raboot', 'cinderace'],
    ['scraggy', 'scrafty'],
    ['scream-tail'],
    ['scyther', 'kleavor'],
    ['scyther', 'scizor'],
    ['seedot', 'nuzleaf', 'shiftry'],
    ['seel', 'dewgong'],
    ['sentret', 'furret'],
    ['seviper'],
    ['sewaddle', 'swadloon', 'leavanny'],
    ['shaymin'],
    ['shellder', 'cloyster'],
    ['shellos', 'gastrodon'],
    ['shelmet', 'accelgor'],
    ['shieldon', 'bastiodon'],
    ['shinx', 'luxio', 'luxray'],
    ['shroodle', 'grafaiai'],
    ['shroomish', 'breloom'],
    ['shuckle'],
    ['shuppet', 'banette'],
    ['sigilyph'],
    ['silicobra', 'sandaconda'],
    ['sinistea', 'polteageist'],
    ['sizzlipede', 'centiskorch'],
    ['skarmory'],
    ['skiddo', 'gogoat'],
    ['skitty', 'delcatty'],
    ['skorupi', 'drapion'],
    ['skrelp', 'dragalge'],
    ['skwovet', 'greedent'],
    ['slakoth', 'vigoroth', 'slaking'],
    ['slither-wing'],
    ['slowpoke', 'slowbro'],
    ['slowpoke', 'slowking'],
    ['slugma', 'magcargo'],
    ['smeargle'],
    ['smoliv', 'dolliv', 'arboliva'],
    ['smoochum', 'jynx'],
    ['sneasel', 'sneasler'],
    ['sneasel', 'weavile'],
    ['snivy', 'servine', 'serperior'],
    ['snom', 'frosmoth'],
    ['snorunt', 'froslass'],
    ['snorunt', 'glalie'],
    ['snover', 'abomasnow'],
    ['snubbull', 'granbull'],
    ['sobble', 'drizzile', 'inteleon'],
    ['solosis', 'duosion', 'reuniclus'],
    ['solrock'],
    ['spearow', 'fearow'],
    ['spectrier'],
    ['spheal', 'sealeo', 'walrein'],
    ['spinarak', 'ariados'],
    ['spinda'],
    ['spiritomb'],
    ['spoink', 'grumpig'],
    ['sprigatito', 'floragato', 'meowscarada'],
    ['spritzee', 'aromatisse'],
    ['squawkabilly'],
    ['squirtle', 'wartortle', 'blastoise'],
    ['stakataka'],
    ['stantler', 'wyrdeer'],
    ['starly', 'staravia', 'staraptor'],
    ['staryu', 'starmie'],
    ['stonjourner'],
    ['stufful', 'bewear'],
    ['stunfisk'],
    ['stunky', 'skuntank'],
    ['suicune'],
    ['sunkern', 'sunflora'],
    ['surskit', 'masquerain'],
    ['swablu', 'altaria'],
    ['swinub', 'piloswine', 'mamoswine'],
    ['swirlix', 'slurpuff'],
    ['tadbulb', 'bellibolt'],
    ['taillow', 'swellow'],
    ['tandemaus', 'maushold'],
    ['tangela', 'tangrowth'],
    ['tapu-bulu'],
    ['tapu-fini'],
    ['tapu-koko'],
    ['tapu-lele'],
    ['tarountula', 'spidops'],
    ['tatsugiri'],
    ['tauros'],
    ['teddiursa', 'ursaring', 'ursaluna'],
    ['tentacool', 'tentacruel'],
    ['tepig', 'pignite', 'emboar'],
    ['terapagos'],
    ['terrakion'],
    ['throh'],
    ['thundurus'],
    ['timburr', 'gurdurr', 'conkeldurr'],
    ['ting-lu'],
    ['tinkatink', 'tinkatuff', 'tinkaton'],
    ['tirtouga', 'carracosta'],
    ['toedscool', 'toedscruel'],
    ['togedemaru'],
    ['togepi', 'togetic', 'togekiss'],
    ['torchic', 'combusken', 'blaziken'],
    ['torkoal'],
    ['tornadus'],
    ['totodile', 'croconaw', 'feraligatr'],
    ['toxel', 'toxtricity'],
    ['trapinch', 'vibrava', 'flygon'],
    ['treecko', 'grovyle', 'sceptile'],
    ['tropius'],
    ['trubbish', 'garbodor'],
    ['turtonator'],
    ['turtwig', 'grotle', 'torterra'],
    ['tympole', 'palpitoad', 'seismitoad'],
    ['tynamo', 'eelektrik', 'eelektross'],
    ['type-null', 'silvally'],
    ['tyrogue', 'hitmonchan'],
    ['tyrogue', 'hitmonlee'],
    ['tyrogue', 'hitmontop'],
    ['tyrunt', 'tyrantrum'],
    ['unown'],
    ['uxie'],
    ['vanillite', 'vanillish', 'vanilluxe'],
    ['varoom', 'revavroom'],
    ['veluza'],
    ['venipede', 'whirlipede', 'scolipede'],
    ['venonat', 'venomoth'],
    ['victini'],
    ['virizion'],
    ['volbeat'],
    ['volcanion'],
    ['voltorb', 'electrode'],
    ['vullaby', 'mandibuzz'],
    ['vulpix', 'ninetales'],
    ['wailmer', 'wailord'],
    ['walking-wake'],
    ['wattrel', 'kilowattrel'],
    ['weedle', 'kakuna', 'beedrill'],
    ['whismur', 'loudred', 'exploud'],
    ['wiglett', 'wugtrio'],
    ['wimpod', 'golisopod'],
    ['wingull', 'pelipper'],
    ['wishiwashi'],
    ['wo-chien'],
    ['woobat', 'swoobat'],
    ['wooloo', 'dubwool'],
    ['wooper', 'clodsire'],
    ['wooper', 'quagsire'],
    ['wurmple', 'cascoon', 'dustox'],
    ['wurmple', 'silcoon', 'beautifly'],
    ['wynaut', 'wobbuffet'],
    ['xerneas'],
    ['xurkitree'],
    ['yamask', 'cofagrigus'],
    ['yamask', 'runerigus'],
    ['yamper', 'boltund'],
    ['yanma', 'yanmega'],
    ['yungoos', 'gumshoos'],
    ['yveltal'],
    ['zacian'],
    ['zamazenta'],
    ['zangoose'],
    ['zapdos'],
    ['zarude'],
    ['zekrom'],
    ['zeraora'],
    ['zigzagoon', 'linoone', 'obstagoon'],
    ['zorua', 'zoroark'],
    ['zubat', 'golbat', 'crobat'],
    ['zygarde'],
]